frontend/src/components/home/Home.jsx
frontend/src/redux/actions/app.js
frontend/src/redux/actions/types.js
frontend/src/redux/reducers/appReducer.js
frontend/src/utils/api.js

Example on redux

---

frontend/src/components/admin/subs/NotificationModal/NotificationModal.jsx

The Admin Notification Settings modal has been completed. issues #227

Completed the Admin Notification Settings modal

---

frontend/src/components/admin/subs/MessageBoardTop/EachMessage.jsx
frontend/src/components/admin/subs/NotificationModal/NotificationModal.jsx

The Admin Message Board Top and Admin Notification Settings Modal has been completed. Props passed into components where optimised.

edited the completed issues #226 and #227

---

frontend/src/components/MessageBoard/subs/ChannelDetailsContainer/ChannelDetailsContainer.jsx

Created ChannelDetailsContainer folder and ChannelDetailsContainer.jsx
Finished coding the component

Finished Channel Details Container Component

---

frontend/src/components/UserProfile/UserProfile.jsx
frontend/src/components/UserProfile/UserProfileHeader.jsx

after i develop the header ui i export it and import back to userprofile.jsx

export userProfileHeader

---

frontend/src/components/MessageBoard/MessageList.jsx
frontend/yarn.lock

Create Messages Component
Reviewer: mrkendrick

Create Messages Component

---

frontend/src/components/TempSidebar/Channels.jsx

added dynamic data to render elements

---

frontend/src/components/admin/subs/ChannelNameBanner/ChannelNameBanner.jsx
frontend/src/components/home/Home.jsx

Created ChannelNameBanner component.

Channels Details & Setting - Channel Name Banner

---

frontend/src/components/MessageBoard/subs/InputFieldComponent/InputFieldComponent.jsx
frontend/src/components/admin/index.jsx
frontend/src/components/admin/subs/ChannelNameBanner/ChannelNameBanner.jsx
frontend/src/components/admin/subs/MessageBoardTop/EachMessage.jsx
frontend/src/components/admin/subs/MessageBoardTop/MessageBoardTop.jsx
frontend/src/components/admin/subs/MessageInput.jsx
frontend/src/components/admin/subs/NotificationModal/NotificationModal.jsx
frontend/src/components/admin/subs/channelDetails/MoreOption.jsx
frontend/src/components/admin/subs/channelDetails/index.jsx

Admin Interface implemented
Fixed design issues

Admin Interface implemented

---

frontend/src/components/admin/subs/channelDetails/channelAbout/about.jsx
frontend/src/components/admin/subs/channelDetails/channelAbout/editable.jsx

add channel about section for #251

---

frontend/src/components/createChannel/addPeopleModal.jsx

#235 
create add member to channel component

create add member to channel component

---

backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

Endpoint to retrieve information about a channel.
Issue #338

Channel retrieve endpoint #338

---

backend/channel_plugin/apps/channels/serializers.py
backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

Created API Endpoint for Creating Channels. Closes #357

Created Create Channel Endpoint

---

backend/channel_plugin/apps/channels/serializers.py
backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

This commit fixes issue #137 
Created endpoint to send messages in a channel.

Send message in channel #137

---

frontend/src/components/thread/subs/MainMessage.jsx

Linked Issues #257 
Reviewer @mrkendrick 
Assignees @ahmad-cod

Patience.fe dev

---

backend/channel_plugin/apps/channels/serializers.py
backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

worked on Thread creation API endpoint.  issue #347

Solve Issue #347 Thread(create) endpoint

---

frontend/src/components/thread/Thread.jsx

thread main component name change

---

backend/channel_plugin/apps/channels/serializers.py
backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

Thread update endpoint #350

---

backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

Update on channel user roles delete

---

frontend/src/components/channelDetailsAndSetting/TabsRow.jsx
frontend/src/components/channelDetailsAndSetting/channelDetailsAndSettings.jsx
frontend/src/components/channelDetailsAndSetting/organisationMembersList.jsx

Made changes to align component with modal

Abraham fe - Changes to organisation list component

---

frontend/src/components/channelDetailsAndSetting/channelDetailsAndSettings.jsx

Abraham FE - Changed tab color

---

frontend/src/components/MessageBoard/MessageBoardIndex.jsx
frontend/src/components/MessageBoard/subs/ChannelDetailsContainer/ChannelDetailsContainer.jsx
frontend/src/components/createChannel/createChannelModal.jsx
frontend/src/components/home/Home.jsx

removed some buttons in the home.jsx and set it for presentation

set the buttons up for presentation

---

backend/channel_plugin/channel_plugin/info/views.py

I added the v1 to the link and edited the return data. Tasks left: 1. Authentication from ZC_Core 2. Actual Retrieval

Sidebar url update

---

frontend/src/components/OnclickuserProfile.jsx
frontend/src/components/UserProfile/OnclickuserProfile.jsx
frontend/src/components/UserProfile/UserProfile.jsx
frontend/src/components/UserProfile/UserProfileOnHover.jsx

userprofile component both web/mobile veiw
@mrkendrick

 refactored my code #working on userprofile component

---

frontend/src/components/MessageBoard/subs/MessageCardContainer/MessageCardContainer.jsx
frontend/src/components/admin/subs/channelDetails/index.jsx
frontend/src/components/shared/MessageCard.jsx

Pin Message Workflow - Add Message Options

---

frontend/src/components/channelDetailsAndSetting/organisationMembersList.jsx

@mrkendrick 
New update on User-Profile

devLEASH-FE New update on User-Profile

---

backend/channel_plugin/apps/channels/serializers.py
backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

Endpoints to retrieve and update notification preferences for a user per channel

feat: user notifications endpoints. be.wrecodde

---

backend/channel_plugin/apps/channels/serializers.py
backend/channel_plugin/apps/channels/urls.py
backend/channel_plugin/apps/channels/views.py

Reverts zurichat/zc_plugin_channels#544

Revert "feat: user notifications endpoints. be.wrecodde"

---

backend/channel_plugin/apps/channelmessages/serializers.py
backend/channel_plugin/apps/channelmessages/urls.py
backend/channel_plugin/apps/channelmessages/views.py

A pull request for message reaction workflow

Manage message reactions

---

frontend/package.json
frontend/src/components/shared/MessageInput.jsx
frontend/yarn.lock

Added the emoji picker function written by AYBAMZZ

Input Component Field with Emoji PIcker

---

frontend/src/components/UserProfile/OnclickuserProfile.jsx
frontend/src/components/UserProfile/UserProfile.jsx
frontend/src/components/channelDetailsAndSetting/TabsRow.jsx
frontend/src/components/channelDetailsAndSetting/channelDetailsAndSettings.jsx

fixed a bug in userprofile
@mrkendrick

devLEASH-FE fixed a bug in userprofile

---

frontend/src/components/shared/DeleteChannel.jsx
frontend/src/components/shared/DisplayAndDownloadFiles.jsx
frontend/src/components/shared/DisplayFile.jsx
frontend/src/redux/actions/app.js
frontend/src/redux/actions/types.js
frontend/src/redux/reducers/appReducer.js
frontend/src/redux/reducers/channelsReducer.js
frontend/src/utils/api.js

Osomhe.fe dev

---

frontend/main/src/components/shared/PinnedMessages.jsx
frontend/main/src/redux/actions/app.js

Adjust pin message response to git response model
Adjust component height to fit messages quantity

Adjust PinnedMessages height to fit messages quantity

---

backend/channel_plugin/apps/centri/signals.py
backend/channel_plugin/apps/channelmessages/views.py
backend/channel_plugin/channel_plugin/utils/wrappers.py
backend/channel_plugin/rtc_schema.json

Reverts zurichat/zc_plugin_channels#600

Revert "Patch for channelmessage RTC"

---

frontend/main/src/components/shared/ChannelHeader.jsx
frontend/main/src/components/shared/MessageInput.jsx

Also fixed isPrivate conditional statement in channel header

changed org id in message input and channel header

---

frontend/main/src/components/shared/DeleteMessage.jsx

Created the Delete Message Modal.jsx

Created DeleteMessage.jsx

---

frontend/main/src/components/channelDetailsAndSetting/channelDetailsAndSettings.jsx
frontend/main/src/components/channelDetailsAndSetting/fileList.jsx
frontend/main/src/components/shared/ChannelHeader.jsx

Integrated channel detail and setting with header component

Abraham og fe - Channel Detail and Settings update

---

backend/channel_plugin/apps/centri/templates/centri/index.html
backend/channel_plugin/config/settings/local.py

Reverts zurichat/zc_plugin_channels#693

Revert "Fix to allow centrifugo connections over local host"

---

frontend/src/components/shared/DeleteChannel.jsx

update UI of delete channel

---

frontend/main/src/components/shared/MoreNotificationModal.jsx

Updated the UI of More Notification Modal.

Update modal UI

---

backend/channel_plugin/apps/channelmessages/views.py
backend/channel_plugin/apps/channels/views.py
backend/channel_plugin/docs/channels.md
backend/channel_plugin/docs/refresh.py
backend/channel_plugin/docs/swagger.yaml

Submit docs

---

frontend/main/.eslintrc
frontend/main/src/components/channelDetailsAndSetting/channelDetailsAndSettings.jsx
frontend/main/src/components/channelDetailsAndSetting/fileList.jsx

Commented out About and files list from the channel header and update the .eslintBabel file

Update to various files

---

frontend/main/src/components/channelDetailsAndSetting/Edit.jsx
frontend/main/src/components/channelDetailsAndSetting/about.jsx
frontend/main/src/components/channelDetailsAndSetting/channelDetailsAndSettings.jsx

Edit component was extracted from the About file into a new file an dAbout has been successfully imported into channel details and settings

Update to About.jsx

---

frontend/main/src/components/MessageBoard/MessageBoardIndex.jsx

Reverts zurichat/zc_plugin_channels#776

Revert "Made the orgId dynamic"

---

frontend/main/src/components/MessageBoard/MessageBoardIndex.jsx
frontend/main/src/components/MessageBoard/subs/MessageCardContainer/MessageCardContainer.jsx
frontend/main/src/components/shared/ChannelHeader.jsx
frontend/main/src/components/shared/MessageCard.jsx
frontend/main/src/components/shared/PinnedMessages.jsx
frontend/main/src/redux/actions/app.js

Reverts zurichat/zc_plugin_channels#782

Revert "PinnedMessage functionality and UI"

---

frontend/main/package.json
frontend/main/src/components/MessageBoard/MessageBoardIndex.jsx
frontend/main/src/components/MessageBoard/subs/MessageCardContainer/MessageCardContainer.jsx
frontend/main/src/components/shared/MessageCard.jsx
frontend/main/src/components/thread/Thread.jsx
frontend/main/src/components/thread/subs/ThreadHeader.jsx
frontend/main/yarn.lock

Reverts zurichat/zc_plugin_channels#785

Revert "Make thread info to display when icon is clicked "

---

frontend/main/src/components/shared/ChannelHeader.jsx

Reverts zurichat/zc_plugin_channels#808

Revert "Fixing the error on live server"

---

backend/channel_plugin/apps/channels/serializers.py

Starring can now be done per user!

Implementing function to star a channel

---

backend/channel_plugin/apps/centri/signals/channel_signals.py
backend/channel_plugin/apps/channels/views.py
frontend/main/src/components/MessageBoard/MessageBoardIndex.jsx
frontend/main/src/components/MessageBoard/subs/MessageCardContainer/MessageCardContainer.jsx
frontend/main/src/components/shared/ChannelHeader.jsx
frontend/main/src/components/shared/MessageInput.jsx
frontend/main/src/routes/routes.js

Reverts zurichat/zc_plugin_channels#817

Revert "Making some design changes"

---

frontend/main/src/components/MessageBoard/MessageBoardIndex.jsx

Reverts zurichat/zc_plugin_channels#819

Revert "Making some design changes and implementing design changes"

---

backend/channel_plugin/apps/channelmessages/urls.py
backend/channel_plugin/apps/channelmessages/views.py
backend/channel_plugin/channel_plugin/utils/pagination_handler.py

Add Pagination to endpoint result and adapt returned data to new structure.

Workflow search new - Add pagination and adapt to new structure

---

backend/channel_plugin/apps/syncApp/queue_handler.py

Reverts zurichat/zc_plugin_channels#874

Revert "Comms feature  fix (# restored queue clearing function)"
